#!/bin/bash -xe
# Dockerhub build script
installer_url="https://github.com/johan149/thinkbox-deadline-repository/releases/download/10.1.0.12/DeadlineRepository-10.1.0.12-linux-x64-installer.run"
curl -OL $installer_url
installer="*.run"
chmod +x $installer
docker build --build-arg DEADLINE_INSTALLER=$installer -t $IMAGE_NAME .
